volumes:
  example_project_volume:
    name: example_project_volume

services:
  db:
    image: postgres:17-bullseye
    volumes:
      - example_project_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 15432:5432
  
  api:
    environment:
      CORS_HOST: http://localhost:5173
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      SIGNING_KEY: ${SIGNING_KEY}
      WAIT_HOSTS: db:5432
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    user: "1000:1000"
    volumes:
      - ./api:/app
  
  frontend:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      VITE_API_HOST: http://localhost:8000
      BASE_URL: http://localhost:5173
    ports:
      - "5173:5173"
